name: Medicine Reminder Cron

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 1 minute
  workflow_dispatch: # Enables the manual "Run workflow" button

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Create Service Account File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json

      - name: Run Worker Script
        run: node notification-worker.js
